[package]
name = "step_curve"
version = "0.1.1"
edition = "2024_07"

[dependencies]
starknet = "2.8.2"

[lib]
name = "step_curve"
path = "src/lib.cairo"

[[target.starknet-contract]]
sierra = true
casm = true

[scripts]
build = "scarb build"
check = "scarb check"

[dev-dependencies]
snforge_std = "0.52.0"
